logstash:
  enabled: true
  config: |
    input {
        generator {
            type => "dummy"
            count => -1
            message => '{"message": "dummy log"}'
        }
    }

    filter {
        json {
            source => "message"
        }
    }

    output {
        elasticsearch {
            hosts => ["http://logstash-integration-test-chart:9200"]
        }
    }

prometheus:
  enabled: true
  alertmanager:
    enabled: false
  kube-state-metrics:
    enabled: false
  service:
    type: ClusterIP
  config: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "logstash-exporter"
        scrape_interval: 5s
        scrape_timeout: 5s
        metrics_path: "/metrics"
        scheme: "http"
        static_configs:
          - targets: ["exporter:9198"]

apache:
  enabled: true
  service:
    type: ClusterIP

logstash-exporter:
  enabled: true
  fullnameOverride: logstash-exporter
  image:
    repository: logstash-exporter
    tag: latest
    pullPolicy: IfNotPresent
